FROM python:3.10-slim

# 필수 패키지 (vim, curl은 디버깅이랑 healthcheck 용)
RUN apt-get update && apt-get install -y \
    curl \
    vim \
    && rm -rf /var/lib/apt/lists/*

# 작업 디렉토리
WORKDIR /app

# 필수 의존성 설치
RUN pip install --no-cache-dir \
    gradio \
    openai

# 코드 복사
COPY webui/webui.py .

# Gradio 실행
CMD ["python", "webui.py"]
